server:
  port: 8088

spring:
  application:
    name: msa-weather-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:piyongze/config.git
          search-paths: repo
  rabbitmq:
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8086/eureka/

logging:
  config: classpath:logback.xml

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh